#!/bin/bash

IP=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')
printf "------------------------------------------"
printf "OpenFLIXR Media Server: \033[36mhttp://$IP \033[0m"
printf "Configure: \033[32mhttp://$IP/setup\033[0m"
