#!/bin/bash

IP=$(hostname -I | awk '{print $1}')
echo "------------------------------------------"
echo -e "OpenFLIXR Media Server: \033[36mhttp://$IP \033[0m"
echo -e "Setup Web: \033[32mhttp://$IP/setup\033[0m"
echo -e "Setup SSH: \033[32msudo setupopenflixr\033[0m"
