#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
            exit 1
    fi
    
readonly ARGS=("$@")
cd /opt/OpenFLIXR2.SetupScript
bash main.sh "${ARGS[@]:-}"
