#!/bin/bash
exec 1> >(tee -a /var/log/updateof.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:	     $TODAY"
echo "-----------------------------------------------------"

THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
            exit  1
    fi

## OpenFLIXR
echo ""
echo "OpenFLIXR updates:"
cd /opt/update
git pull
cp /opt/update/updates/openflixr/apt-get-queue /opt/openflixr/apt-get-queue
cp /opt/update/updates/openflixr/blocklist.sh /opt/openflixr/blocklist.sh
chmod +x /opt/openflixr/blocklist.sh
cp /opt/update/updates/openflixr/ipaddress /opt/openflixr/ipaddress
chmod +x /opt/openflixr/ipaddress
cp /opt/update/updates/openflixr/checkinet /opt/openflixr/checkinet
chmod +x /opt/openflixr/checkinet
cp /opt/update/updates/openflixr/purgeoldkernels /opt/openflixr/purgeoldkernels
chmod +x /opt/openflixr/purgeoldkernels
cp /opt/update/updates/openflixr/startup.sh /opt/openflixr/startup.sh
chmod +x /opt/openflixr/startup.sh
cp /opt/update/updates/openflixr/updatewkly.sh /opt/openflixr/updatewkly.sh
chmod +x /opt/openflixr/updatewkly.sh
cp /opt/update/updates/openflixr/updateof /opt/openflixr/updateof
chmod +x /opt/openflixr/updateof
cp /opt/update/updates/openflixr/createdirs /opt/openflixr/createdirs
chmod +x /opt/openflixr/createdirs
cp /opt/update/updates/openflixr/logio.sh /opt/openflixr/logio.sh
chmod +x /opt/openflixr/logio.sh
cp /opt/update/updates/openflixr/hotfixes /opt/openflixr/hotfixes
cp /opt/update/updates/monit/* /etc/monit/conf.d/
cp /opt/update/updates/openflixr/createnginxconfig.sh /opt/openflixr/createnginxconfig.sh
chmod +x /opt/openflixr/createnginxconfig.sh
cp /opt/update/updates/openflixr/letsencrypt.sh /opt/openflixr/letsencrypt.sh
chmod +x /opt/openflixr/letsencrypt.sh
cp /opt/update/updates/openflixr/cleanup.sh /opt/openflixr/cleanup.sh
chmod +x /opt/openflixr/cleanup.sh

## Nginx config
echo ""
echo "Create nginx config:"
bash /opt/openflixr/createnginxconfig.sh

## Create Download dirs when mounted to a network share
cd /opt/openflixr
echo ""
echo "create download dirs:"
bash createdirs

## hotfixes
bash /opt/openflixr/hotfixes

## User script
bash /opt/openflixr/userscript.sh

## let setup know updateof finished
echo "updateof finished"
