---
auth:
  authType: "NONE"
  rememberUsers: true
  rememberMeValidityDays: 14
  restrictAdmin: false
  restrictDetailsDl: false
  restrictIndexerSelection: false
  restrictSearch: false
  restrictStats: false
  users: []
categoriesConfig:
  enableCategorySizes: true
  categories:
  - name: "Anime"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - 5070
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 3000
    minSizePreset: 50
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "ANIME"
  - name: "Audio"
    mayBeSelected: true
    searchType: "MUSIC"
    newznabCategories:
    - 3000
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords:
    - "mp3"
    - "flac"
    maxSizePreset: 2000
    minSizePreset: 1
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Audiobook"
    mayBeSelected: true
    searchType: "MUSIC"
    newznabCategories:
    - 3030
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 1000
    minSizePreset: 50
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "AUDIOBOOK"
  - name: "Comic"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - 7030
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 250
    minSizePreset: 1
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "COMIC"
  - name: "Console"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - 1000
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 40000
    minSizePreset: 100
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Ebook"
    mayBeSelected: true
    searchType: "BOOK"
    newznabCategories:
    - 7020
    - 8010
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 100
    minSizePreset: null
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "EBOOK"
  - name: "FLAC"
    mayBeSelected: true
    searchType: "MUSIC"
    newznabCategories:
    - 3040
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 2000
    minSizePreset: 10
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Movies"
    mayBeSelected: true
    searchType: "MOVIE"
    newznabCategories:
    - 2000
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 20000
    minSizePreset: 500
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Movies HD"
    mayBeSelected: true
    searchType: "MOVIE"
    newznabCategories:
    - 2040
    - 2050
    - 2060
    - 2070
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 20000
    minSizePreset: 3000
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Movies SD"
    mayBeSelected: true
    searchType: "MOVIE"
    newznabCategories:
    - 2030
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 3000
    minSizePreset: 500
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "MP3"
    mayBeSelected: true
    searchType: "MUSIC"
    newznabCategories:
    - 3010
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 500
    minSizePreset: 1
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "PC"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - 4000
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 50000
    minSizePreset: 100
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "TV"
    mayBeSelected: true
    searchType: "TVSEARCH"
    newznabCategories:
    - 5000
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 5000
    minSizePreset: 50
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "TV HD"
    mayBeSelected: true
    searchType: "TVSEARCH"
    newznabCategories:
    - 5040
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 4500
    minSizePreset: 300
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "TV SD"
    mayBeSelected: true
    searchType: "TVSEARCH"
    newznabCategories:
    - 5030
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 1000
    minSizePreset: 50
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "XXX"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - 6000
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 10000
    minSizePreset: 100
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
downloading:
  downloaders: []
  saveTorrentsTo: "/mnt/downloads/torrentwatch"
  sendMagnetLinks: true
  updateStatuses: true
indexers: []
main:
  apiKey: "aqpep52c61fkbc8br0tiu53508"
  configVersion: 3
  backupEverySunday: true
  backupBeforeUpdate: true
  deleteBackupsAfterWeeks: 4
  dereferer: "http://www.dereferer.org/?$s"
  host: "0.0.0.0"
  logging:
    consolelevel: "INFO"
    historyUserInfoType: "NONE"
    logIpAddresses: true
    logMaxHistory: 30
    logfilelevel: "INFO"
    logUsername: false
    markersToLog: []
  port: 5075
  proxyType: "NONE"
  proxyHost: null
  proxyPort: 1080
  proxyIgnoreLocal: true
  proxyIgnoreDomains: []
  proxyUsername: null
  proxyPassword: null
  repositoryBase: "https://github.com/theotherp"
  showNews: true
  shutdownForRestart: false
  sniDisabledFor:
  - "nzbgeek.info"
  ssl: false
  sslKeyStore: null
  sslKeyStorePassword: null
  startupBrowser: false
  theme: "grey"
  urlBase: "/nzbhydra"
  updateCheckEnabled: true
  useCsrf: false
  usePackagedCaCerts: true
  verifySsl: true
  welcomeShown: true
  xmx: 128
searching:
  applyRestrictions: "NONE"
  duplicateAgeThreshold: 2.0
  duplicateSizeThresholdInPercent: 1.0
  forbiddenGroups: []
  forbiddenPosters: []
  forbiddenRegex: null
  forbiddenWords: []
  generateQueries: "NONE"
  idFallbackToQueryGeneration: "NONE"
  ignorePassworded: false
  ignoreTemporarilyDisabled: false
  keepSearchResultsForDays: 14
  language: "en_US:"
  loadAllCachedOnInternal: true
  maxAge: null
  nzbAccessType: "REDIRECT"
  removeTrailing:
  - ".mp4"
  - ".mkv"
  - ".subs"
  - ".REPOST"
  - "repost"
  - "~DG~"
  - ".DG"
  - "-DG"
  - "-1"
  - ".1"
  - "(1)"
  - "ReUp"
  - "ReUp2"
  - "-RP"
  - "-AsRequested"
  - "-Obfuscated"
  - "-Scrambled"
  - "-Chamele0n"
  - "-BUYMORE"
  - "-[TRP]"
  - "-DG"
  - ".par2"
  - ".part01"
  - "part01.rar"
  - ".part02.rar"
  - ".jpg"
  - "[rartv]"
  - "[rarbg]"
  - "[eztv]"
  - "English"
  - "Korean"
  - "Spanish"
  - "French"
  - "German"
  - "Italian"
  - "Danish"
  - "Dutch"
  - "Japanese"
  - "Cantonese"
  - "Mandarin"
  - "Russian"
  - "Polish"
  - "Vietnamese"
  - "Swedish"
  - "Norwegian"
  - "Finnish"
  - "Turkish"
  - "Portuguese"
  - "Flemish"
  - "Greek"
  - "Hungarian"
  requiredRegex: null
  requiredWords: []
  showQuickFilterButtons: true
  timeout: 20
  userAgent: "NZBHydra2"
  userAgents:
  - "Mozilla"
  - "Sonarr"
  - "Radarr"
  - "CouchPotato"
  - "LazyLibrarian"
  - "NZBGet"
  - "sabNZBd"
  useOriginalCategories: false
  wrapApiErrors: false
