#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            printf 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/a_update_1.log) 2>&1
TODAY=$(date)
printf "-----------------------------------------------------"
printf "Date:          $TODAY"
printf "-----------------------------------------------------"

## OpenFLIXR Update version 2.0.0
## let system know update has been installed
touch /opt/update/doneupdate/a_update_1
