#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/b_update_2.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 2.0
# script updates
cp /opt/update/updates/openflixr/updatewkly.sh /opt/openflixr/updatewkly.sh
chmod +x /opt/openflixr/updatewkly.sh
cp /opt/update/updates/openflixr/updateof /opt/openflixr/updateof
chmod +x /opt/openflixr/updateof
cp /opt/update/updates/openflixr/ipaddress /opt/openflixr/ipaddress
chmod +x /opt/openflixr/ipaddress

## fixes
rm /etc/dhcpcd.conf

## let system know update has been installed
touch /opt/update/doneupdate/b_update_2
