#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/c_update_3.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 2.0.1

# fixes
pihole -b analytics.plex.tv
cd /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/
rm Preferences.xml

## let system know update has been installed
touch /opt/update/doneupdate/c_update_3
