#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/d_update_4.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 2.2

# fixes
cp -R /opt/update/latest/* /usr/share/nginx/html/latest

# homeassistant
add-apt-repository ppa:deadsnakes/ppa -y

# plex update
rm -rf /opt/plexupdate
echo deb https://downloads.plex.tv/repo/deb public main | sudo tee /etc/apt/sources.list.d/plexmediaserver.list
curl https://downloads.plex.tv/plex-keys/PlexSign.key | sudo apt-key add -

# fix syncthing
rm -r /home/openflixr/.config/syncthing/*
service syncthing@openflixr start
service syncthing@openflixr stop
sed -i 's/<theme>default<\/theme>/<theme>dark<\/theme><insecureSkipHostcheck>true<\/insecureSkipHostcheck>/' /home/openflixr/.config/syncthing/config.xml
sed -i 's/<startBrowser>true<\/startBrowser>/<startBrowser>false<\/startBrowser>/' /home/openflixr/.config/syncthing/config.xml
sed -i 's/<urAccepted>0<\/urAccepted>/<urAccepted>-1<\/urAccepted>/' /home/openflixr/.config/syncthing/config.xml

# Fix latest page
cp /opt/update/latest/inc/imdb_class.php /usr/share/nginx/html/latest/inc/imdb_class.php
chmod 755 /usr/share/nginx/html/latest/inc/imdb_class.php
chown www-data:www-data /usr/share/nginx/html/latest/inc/*

#misc
cd /opt/letsencrypt
rm -fr .git
git init
git remote add origin https://github.com/certbot/certbot
git fetch
git reset --mixed origin/master
git branch --set-upstream-to=origin/master master
rm /opt/openflixr/updateplex.sh

## let system know update has been installed
touch /opt/update/doneupdate/d_update_4
