#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/e_update_5.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 2.3

# ombi
systemctl stop plexrequestsnet
systemctl disable plexrequestsnet
rm /etc/systemd/system/plexrequestsnet.service
rm /etc/monit/conf.d/plexrequests
systemctl daemon-reload
systemctl reset-failed
cp /opt/update/updates/configs/ombi.service /etc/systemd/system/ombi.service
systemctl daemon-reload
systemctl enable ombi.service
cp /opt/update/updates/monit/ombi /etc/monit/conf.d/ombi
cp /opt/update/updates/monit/ombi /opt/config/monit/ombi

# misc
sed -i 's/net.ipv4.tcp_tw_recycle = 1//' /etc/sysctl.conf
sed -i 's/net.ipv4.tcp_tw_reuse = 1/net.ipv4.tcp_tw_reuse = 0/' /etc/sysctl.conf
sysctl -p
pip2 install -U cryptography idna pyopenssl
pip2 install --upgrade pip
pip uninstall --yes Mopidy-Spotmop
pip3 uninstall --yes Mopidy-Spotmop
pip3.5 uninstall --yes Mopidy-Spotmop
chown -R openflixr:openflixr /opt/sickrage/.git
sed -i 's/<theme>default<\/theme>/<theme>dark<\/theme><insecureSkipHostcheck>true<\/insecureSkipHostcheck>/' /home/openflixr/.config/syncthing/config.xml
crudini --set /opt/LazyLibrarian/lazylibrarian.ini General audio_dir "/mnt/audiobooks"
autorun=$(crudini --get /root/.config/qBittorrent/qBittorrent.conf AutoRun enabled)
if [ "$autorun" == 'false' ]
  then
    crudini --set /root/.config/qBittorrent/qBittorrent.conf AutoRun enabled true
    crudini --set /root/.config/qBittorrent/qBittorrent.conf AutoRun program "chmod -R 777 %R"
  fi

# ubooquity
update-rc.d -f ubooquity remove
rm /etc/init.d/ubooquity
cd /tmp
wget http://vaemendis.net/ubooquity/downloads/Ubooquity-2.1.1.zip
unzip /tmp/Ubooquity-2.1.1.zip
cp /tmp/Ubooquity.jar /opt/ubooquity/
cp /opt/update/updates/configs/ubooquity.service /etc/systemd/system/ubooquity.service
cp /opt/update/updates/configs/preferences.json /opt/ubooquity/
mv /opt/ubooquity/preferences.xml /opt/ubooquity/preferences.xml.bak
systemctl daemon-reload
systemctl enable ubooquity.service
git clone https://github.com/FinalAngel/plextheme /opt/ubooquity/themes/plextheme

## let system know update has been installed
touch /opt/update/doneupdate/e_update_5
