#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/g_update_7.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 2.4.3
# script updates
cp /opt/update/updates/openflixr/updatewkly.sh /opt/openflixr/updatewkly.sh
chmod +x /opt/openflixr/updatewkly.sh

## update version
sed -i 's/2.*/2.4.3 A Better Tomorrow II/' /opt/openflixr/version
crudini --set /usr/share/nginx/html/setup/config.ini custom custom1 2.4.3
version=$(crudini --get /usr/share/nginx/html/setup/config.ini custom custom1)
sed -i 's/Version.*/Version '$version'<\/span>/' /usr/share/nginx/html/openflixr/index.html

## let system know update has been installed
touch /opt/update/doneupdate/g_update_7

# update system weekly
bash /opt/openflixr/updatewkly.sh

# reboot system just to be sure
reboot now
