#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/h_update_8.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 2.5
service monit stop

# nginx php 7.2
sed -i 's/php5-fpm.sock/php\/php7.2-fpm.sock/' /etc/nginx/sites-available/reverse
sed -i 's/php7.0-fpm.sock/php7.2-fpm.sock/g' /etc/nginx/sites-enabled/reverse

# grav fixes
chown www-data:www-data -R /usr/share/nginx/html/user
chown www-data:www-data -R /usr/share/nginx/html/cache
chmod +777 -R /usr/share/nginx/html/cache
cd /usr/share/nginx/html
bin/gpm selfupgrade -f -y
bin/gpm update -f -y
sed -i 's/index index.html index.php;/index index.php;/' /etc/nginx/sites-enabled/reverse

# lidarr fix
mkdir /home/openflixr/.config/Lidarr
chmod +777 -R /home/openflixr/.config/Lidarr
chown openflixr: -R /home/openflixr/.config/Lidarr

if [ ! -f /home/openflixr/.config/Lidarr/config.xml ]; then
  cp /opt/update/updates/configs/config.xml /home/openflixr/.config/Lidarr/config.xml
fi

# ombi fix
cp /opt/update/updates/configs/ombi.service /etc/systemd/system/ombi.service
systemctl daemon-reload
systemctl enable ombi.service

# nzbhydra2
systemctl stop nzbhydra
systemctl disable nzbhydra
rm /etc/systemd/system/nzbhydra.service
cp /opt/update/updates/monit/nzbhydra /etc/monit/conf.d/nzbhydra
cp /opt/update/updates/monit/nzbhydra /opt/config/monit/nzbhydra
cp /opt/update/updates/configs/nzbhydra2.service /etc/systemd/system/nzbhydra2.service
systemctl daemon-reload
systemctl reset-failed
systemctl enable nzbhydra2.service
mkdir /opt/nzbhydra2
wget https://raw.githubusercontent.com/theotherp/nzbhydra2/master/other/wrapper/nzbhydra2wrapper.py -O /opt/nzbhydra2/nzbhydra2wrapper.py

wasactive=$(systemctl is-active nzbhydra2)
link=$(wget -q https://github.com/theotherp/nzbhydra2/releases/latest -O - | grep -i href | grep -i linux.zip | awk -F "[\"]" '{print $2}')
latestver=$(echo $link | awk -F "[\/]" '{print $6}')
latestverurl=$(echo $link | awk -F "[\/]" '{print $1"/"$2"/"$3"/"$4"/"$5"/"$6"/"$7}')
link='https://github.com'$latestverurl
# Write some stuff to the log so we know what happened if it goes wrong
echo latestver = $latestver
  echo "NZBhydra2 needs updating"
  echo "download link = $link"
  service nzbhydra2 stop
  cd /tmp/
  rm nzbhydra2* 2> /dev/null
  wget -q $link || echo 'Download failed!'
  unzip nzbhydra2*.zip -d /opt/nzbhydra2/
  rm nzbhydra2* 2> /dev/null
  chown openflixr: -R /opt/nzbhydra2
  if [ $wasactive == "active" ]
  then
    echo "Starting NZBhydra2 after update"
    service nzbhydra2 start
  else
    echo "NZBhydra2 was not running before, so not starting it now"
  fi

service nzbhydra2 start
service nzbhydra2 stop
cp /opt/update/updates/configs/nzbhydra.yml /opt/nzbhydra2/data/nzbhydra.yml

# package updates
apt-get update -y
apt-get purge apache2 php7.1* php7.0* -y
systemctl disable lighttpd.service
systemctl disable apache2
systemctl enable nginx
DEBIAN_FRONTEND=noninteractive apt-get -y --with-new-pkgs upgrade
bash /opt/openflixr/apt-get-queue php7.2-dev php7.2-fpm ombi sshfs vim python-cairocffi python3-cairocffi php7.2-zip php7.2-common libzip5 python-cffi python-pycparser python3-ply python3-cffi-backend python3-cffi python3-pycparser python-ply python3.6 python3.6-venv python3.6-dev
sudo -H pip install psycopg2-binary
python3.6 -m pip install homeassistant --upgrade pip
rm /etc/systemd/system/plexrequestsnet.service

# kernel update fix
cd /tmp/
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.17.5/linux-headers-4.17.5-041705_4.17.5-041705.201807081431_all.deb
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.17.5/linux-headers-4.17.5-041705-generic_4.17.5-041705.201807081431_amd64.deb
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.17.5/linux-modules-4.17.5-041705-generic_4.17.5-041705.201807081431_amd64.deb
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.17.5/linux-image-unsigned-4.17.5-041705-generic_4.17.5-041705.201807081431_amd64.deb
sudo dpkg -i linux-headers-4.17.5-041705_4.17.5-041705.201807081431_all.deb
sudo dpkg -i linux-headers-4.17.5-041705-generic_4.17.5-041705.201807081431_amd64.deb
sudo dpkg -i linux-modules-4.17.5-041705-generic_4.17.5-041705.201807081431_amd64.deb
sudo dpkg -i linux-image-unsigned-4.17.5-041705-generic_4.17.5-041705.201807081431_amd64.deb

## update version
sed -i 's/2.*/2.5 A Better Tomorrow III/' /opt/openflixr/version
crudini --set /usr/share/nginx/html/setup/config.ini custom custom1 2.5
version=$(crudini --get /usr/share/nginx/html/setup/config.ini custom custom1)
sed -i 's/Version.*/Version '$version'<\/span>/' /usr/share/nginx/html/openflixr/index.html

## let system know update has been installed
touch /opt/update/doneupdate/h_update_8

# update system weekly
bash /opt/openflixr/updatewkly.sh

# reboot system just to be sure
reboot now
