#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/h_update_8.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 2.5

# grav fixes
chown www-data:www-data -R /usr/share/nginx/html/user
chown www-data:www-data -R /usr/share/nginx/html/cache
chmod +777 -R /usr/share/nginx/html/cache
cd /usr/share/nginx/html
bin/gpm selfupgrade -f -y
bin/gpm update -f -y

# lidarr fix
mkdir /home/openflixr/.config/Lidarr
chmod +777 -R /home/openflixr/.config/Lidarr
chown openflixr: -R /home/openflixr/.config/Lidarr

if [ ! -f /home/openflixr/.config/Lidarr/config.xml ]; then
  cp /opt/update/updates/configs/config.xml /home/openflixr/.config/Lidarr/config.xml
fi

# ombi fix
cp /opt/update/updates/configs/ombi.service /etc/systemd/system/ombi.service
systemctl daemon-reload
systemctl enable ombi.service

# nzbhydra2
systemctl stop nzbhydra
systemctl disable nzbhydra
rm /etc/systemd/system/nzbhydra.service
cp /opt/update/updates/monit/nzbhydra /etc/monit/conf.d/nzbhydra
cp /opt/update/updates/monit/nzbhydra /opt/config/monit/nzbhydra
cp /opt/update/updates/configs/nzbhydra2.service /etc/systemd/system/nzbhydra2.service
systemctl daemon-reload
systemctl reset-failed
systemctl enable nzbhydra2.service
mkdir /opt/nzbhydra2
wget https://raw.githubusercontent.com/theotherp/nzbhydra2/master/other/wrapper/nzbhydra2wrapper.py -O /opt/nzbhydra2/nzbhydra2wrapper.py

wasactive=$(systemctl is-active nzbhydra2)
link=$(wget -q https://github.com/theotherp/nzbhydra2/releases/latest -O - | grep -i href | grep -i linux.zip | awk -F "[\"]" '{print $2}')
latestver=$(echo $link | awk -F "[\/]" '{print $6}')
latestverurl=$(echo $link | awk -F "[\/]" '{print $1"/"$2"/"$3"/"$4"/"$5"/"$6"/"$7}')
link='https://github.com'$latestverurl
# Write some stuff to the log so we know what happened if it goes wrong
echo latestver = $latestver
  echo "NZBhydra2 needs updating"
  echo "download link = $link"
  service nzbhydra2 stop
  cd /tmp/
  rm nzbhydra2* 2> /dev/null
  wget -q $link || echo 'Download failed!'
  unzip -o nzbhydra2*.zip -d /opt/nzbhydra2/
  rm nzbhydra2* 2> /dev/null
  chown openflixr: -R /opt/nzbhydra2
  if [ $wasactive == "active" ]
  then
    echo "Starting NZBhydra2 after update"
    service nzbhydra2 start
  else
    echo "NZBhydra2 was not running before, so not starting it now"
  fi

service nzbhydra2 start
service nzbhydra2 stop
cp /opt/update/updates/configs/nzbhydra.yml /opt/nzbhydra2/data/nzbhydra.yml

# package updates
systemctl disable lighttpd.service
systemctl disable apache2
systemctl enable nginx
pip install psycopg2-binary
pip3 install psycopg2-binary
rm /etc/systemd/system/plexrequestsnet.service

## let system know update has been installed
touch /opt/update/doneupdate/h_update_8
