#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/i_update_9.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 2.5.1
cd /opt/update
git pull
cp /opt/update/updates/openflixr/apt-get-queue /opt/openflixr/apt-get-queue
cp /opt/update/updates/openflixr/blocklist.sh /opt/openflixr/blocklist.sh
chmod +x /opt/openflixr/blocklist.sh
cp /opt/update/updates/openflixr/checkinet /opt/openflixr/checkinet
chmod +x /opt/openflixr/checkinet
cp /opt/update/updates/openflixr/purgeoldkernels /opt/openflixr/purgeoldkernels
chmod +x /opt/openflixr/purgeoldkernels
cp /opt/update/updates/openflixr/startup.sh /opt/openflixr/startup.sh
chmod +x /opt/openflixr/startup.sh
cp /opt/update/updates/openflixr/updatewkly.sh /opt/openflixr/updatewkly.sh
chmod +x /opt/openflixr/updatewkly.sh
cp /opt/update/updates/openflixr/updateof /opt/openflixr/updateof
chmod +x /opt/openflixr/updateof
cp /opt/update/updates/openflixr/createdirs /opt/openflixr/createdirs
chmod +x /opt/openflixr/createdirs
cp /opt/update/updates/openflixr/logio.sh /opt/openflixr/logio.sh
chmod +x /opt/openflixr/logio.sh
cp /opt/update/updates/openflixr/hotfixes /opt/openflixr/hotfixes

# ombi fix
cp /opt/update/updates/configs/ombi.service /etc/systemd/system/ombi.service
systemctl daemon-reload
systemctl enable ombi.service

# nzbhydra2
cp /opt/update/updates/configs/nzbhydra2.service /etc/systemd/system/nzbhydra2.service
systemctl daemon-reload
systemctl reset-failed
systemctl enable nzbhydra2.service
service nzbhydra2 start
service nzbhydra2 stop
cp /opt/update/updates/configs/nzbhydra.yml /opt/nzbhydra2/data/nzbhydra.yml

## update version
sed -i 's/2.*/2.5.1 A Better Tomorrow III/' /opt/openflixr/version
crudini --set /usr/share/nginx/html/setup/config.ini custom custom1 2.5.1
version=$(crudini --get /usr/share/nginx/html/setup/config.ini custom custom1)
sed -i 's/Version.*/Version '$version'<\/span>/' /usr/share/nginx/html/openflixr/index.html

## let system know update has been installed
touch /opt/update/doneupdate/i_update_9

# update system weekly
bash /opt/openflixr/updatewkly.sh

# reboot system just to be sure
reboot now
