#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/i_update_9.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 2.5.1

# ombi fix
cp /opt/update/updates/configs/ombi.service /etc/systemd/system/ombi.service
systemctl daemon-reload
systemctl enable ombi.service

# nzbhydra2
cp /opt/update/updates/configs/nzbhydra2.service /etc/systemd/system/nzbhydra2.service
systemctl daemon-reload
systemctl reset-failed
systemctl enable nzbhydra2.service
service nzbhydra2 start
service nzbhydra2 stop
cp /opt/update/updates/configs/nzbhydra.yml /opt/nzbhydra2/data/nzbhydra.yml

## let system know update has been installed
touch /opt/update/doneupdate/i_update_9
