#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/j_update_10.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 2.8

# updates
cp /opt/update/updates/configs/nginx.conf /etc/nginx/nginx.conf
cp /opt/update/updates/htpcmanager/openflixr/* /opt/HTPCManager/interfaces/default/css/themes/openflixr
rm /etc/monit/conf.d/dnsmasq
cp -R /opt/update/latest/* /usr/share/nginx/html/latest
crudini --set /opt/Mylar/config.ini Perms chowner openflixr
crudini --set /opt/Mylar/config.ini Perms chgroup openflixr
chown openflixr: -R /opt/Mylar
chown openflixr:openflixr /home/openflixr/.config/Lidarr/config.xml
chown -R www-data: /usr/share/nginx/html/
pip install -U pip setuptools
mv /opt/sickrage/ /opt/sickrage.hijacked
git clone https://github.com/SickChill/SickChill.git /opt/sickrage
cp /opt/sickrage.hijacked/sickbeard.db /opt/sickrage
cp /opt/sickrage.hijacked/failed.db /opt/sickrage
cp /opt/sickrage.hijacked/cache.db /opt/sickrage
cp /opt/sickrage.hijacked/config.ini /opt/sickrage
cp -R /opt/sickrage.hijacked/cache /opt/sickrage/
chown -R openflixr: /opt/sickrage
update-rc.d sickrage disable
update-rc.d -f sickrage remove
rm /etc/init.d/sickrage
cp /opt/sickrage/runscripts/init.systemd /etc/systemd/system/sickrage.service
sed -i 's/sickchill/sickrage/g' /etc/systemd/system/sickrage.service
sed -i 's/SickChill/sickrage/g' /etc/systemd/system/sickrage.service
sed -i 's/User=sickrage/User=openflixr/g' /etc/systemd/system/sickrage.service
sed -i 's/Group=sickrage/Group=openflixr/g' /etc/systemd/system/sickrage.service
sed -i '/Group=openflixr/a TimeoutSec=600' /etc/systemd/system/sickrage.service
systemctl enable sickrage.service
systemctl daemon-reload
crudini --set /root/.config/qBittorrent/qBittorrent.conf Preferences 'WebUI\Address' '*'

## let system know update has been installed
touch /opt/update/doneupdate/j_update_10
